### ISSUE TITLE
US 02.01.01 - Record photo and geolocation of QR code location/object

### ISSUE THREAD

**Issue by Iyury1** [CMPUT301W22T22/ArrayList-Student-#11]
# Summary
As a player, I want to be able to scan QR codes and record a photo of the location or object, and the geolocation of the location or object.

Story Points: 2
Risk Level: Low

# Acceptance Criteria
* [x] Prompt user to take optional photo after QR code is scanned
* [x] User camera to take photo
* [x] Save geolocation to ScannableCode
* [x] Save photo to ScannableCode if photo was taken
* [x] Test

# Test cases
Reference test files that cover this user story

**Comment by vinay-parab** [comment]
The app is able to take a photo and save the geolocation and photo to firebase
