### ISSUE TITLE
Setup Geolocation API

### ISSUE THREAD

**Issue by Iyury1** [CMPUT301W22T22/ArrayList-Student-#32]
# Summary
Setup an app that uses a Geolocation API

# Acceptance criteria
* [x] Find appropriate API
* [x] Incorporate API into app
* [x] set up MapView
* [x] get device current location
* [x] Incorporate API with control panel

- [x] set up an extra GPS location service

**Comment by HyZ7846** [comment]
https://developers.google.com/maps/documentation/android-sdk/start
